# fly.toml app configuration file generated for bilkost on 2026-05-22T15:45:42+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bilkost'
primary_region = 'arn'

[build]

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  memory = '256mb'
  cpus = 1
  memory_mb = 256
